export const exercisesData = [
  "Custom",
    'Aerobics',
    'Basketball',
    'Boxing',
    'Circuit Training',
    'Climbing',
    'CrossFit',
    'Cycling',
    'Dancing',
    'Elliptical Training',
    'Football',
    'Golf',
    'Hiking',
    'Hockey',
    'Interval Training',
    'Jumping Rope',
    'Kickboxing',
    'Lacrosse',
    'Martial Arts',
    'Pilates',
    'Powerlifting',
    'Rock Climbing',
    'Rowing',
    'Running',
    'Skateboarding',
    'Skiing',
    'Snowboarding',
    'Soccer',
    'Softball',
    'Spin Class',
    'Squash',
    'Strength Training',
    'Surfing',
    'Swimming',
    'Table Tennis',
    'Tai Chi',
    'Tennis',
    'Track and Field',
    'Trampoline Jumping',
    'Ultimate Frisbee',
    'Volleyball',
    'Walking',
    'Water Aerobics',
    'Weightlifting',
    'Wrestling',
    'Yoga',
    'Zumba',
  ]
  