/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://obsbcuixqrhizfogo4twkau5ya.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-i7gkwtt6gvcxteckdvgey5amru",
    "aws_cognito_identity_pool_id": "us-east-1:ee63d585-b93c-450a-a4a3-36ebd55acd3a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lKi4Soy1x",
    "aws_user_pools_web_client_id": "4lau3vcd1glmkd1e8r369kbl7e",
    "oauth": {},
    "aws_datastore": "true",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NICKNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
