export const diets = [
    "alcohol-free",
    "balanced",
    "high-fiber",
    "high-protein",
    "keto",
    "kidney friendly",
    "kosher",
    "low-carb",
    "low-fat",
    "low potassium",
    "low-sodium",
    "no oil added",
    "no-sugar",
    "paleo",
    "pescatarian",
    "pork-free",
    "red meat-free",
    "sugar-conscious",
    "vegan",
    "vegetarian",
  ];
  
  export const allergies = [
    "celery-free",
    "crustacean-free",
    "dairy-free",
    "egg-free",
    "fish-free",
    "gluten-free",
    "lupine-free",
    "mustard-free",
    "peanut-free",
    "sesame-free",
    "shellfish-free",
    "soy-free",
    "tree-nut-free",
    "wheat-free",
  ];
  